### ISSUE TITLE
ollama-intel-gpu still restarting

### ISSUE THREAD

**Issue by cernyjan** [mattcurf/ollama-intel-gpu#3]
Hi,
I am fasing this problem after run 'docker-compose -f docker-compose-wsl2.yml up' on Windows notebook with Intel GPU:
![image](https://github.com/user-attachments/assets/092114fd-2423-4336-a71e-6da7d8523c64)
![image](https://github.com/user-attachments/assets/128a8d39-5970-4723-9427-de1f580538c4)

Please help, thank you in advance.

**Comment by cernyjan** [comment]
Problem was in ending and format of the file, after delete of blank ending new line and convert from CLRF into LF, it started to work,. :) 
FROM
![Screenshot 2024-09-21 201355](https://github.com/user-attachments/assets/43f8c37f-276b-485d-8fe7-a12d199b2baa)
INTO
![Screenshot 2024-09-21 201419](https://github.com/user-attachments/assets/741527ef-d9e6-4d8d-9617-8d632ec175c8)

**Comment by cernyjan** [comment]
Anyway, chat with ollama does not work in the very end,. :(
![image](https://github.com/user-attachments/assets/d52eb8a9-3239-4ba1-ba1a-b13559059fd9)
![image](https://github.com/user-attachments/assets/bb4daa13-2314-4244-afc1-9ff20290af42)
![image](https://github.com/user-attachments/assets/7f6c19b0-064c-48f9-99d3-4e8511847668)
![image](https://github.com/user-attachments/assets/04b4a8f5-15ec-4e93-9257-ca80e3e75c1e)

**Comment by mattcurf** [comment]
Unfortunately I also see that Intel integrated graphics for 13th Gen processors and older is not supported. "Intel(R) Iris(R) Xe Graphics.  It does appear to work with 14th Gen Processors and its integrated graphics.  I can updated the README.md to clarify these findings

**Comment by eSlider** [comment]
Integrated Iris Xe GPU on `12th Gen Intel Core i7-12700H` with  `Alder Lake-P GT2 [Iris Xe Graphics] driver: i915`  works fine.

If you run it on linux and have two GPU's like me, to get it works only one GPU could be provided to ollama service at time.

```shell
inxi -G

```

    Graphics:
      Device-1: Intel Alder Lake-P GT2 [Iris Xe Graphics] driver: i915 v: kernel
      Device-2: Intel DG2 [Arc A770M] driver: i915 v: kernel

The device should be mapped eplicitly in `docker-compose.yml`, instead of mapping full `/dev/dri`


List system devices: 
```
$ lsgpu                      
card1                    Intel Dg2 (Gen12)                 drm:/dev/dri/card1       
└─renderD129                                               drm:/dev/dri/renderD129  
card0                    Intel Alderlake_p (Gen12)         drm:/dev/dri/card0       
└─renderD128                                               drm:/dev/dri/renderD128  
```


Docker composition:

```yaml
services:
  ollama-intel-gpu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama-intel-gpu
    image: ollama-intel-gpu:latest
    restart: always
    devices:
      - /dev/dri/renderD129:/dev/dri/renderD129
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ollama-intel-gpu:/root/.ollama
```

**Comment by eSlider** [comment]
I would like to note that the speed of inference through the integrated GPU, evaluated visually, is less than two times inferior, which is also an excellent result, compared to the speed on a bare CPU.

If you want to use both GPUs at once, this is how it works in parallel:

## docker-compose.yml

```yaml
services:                                                                                     
  ollama-intel-arc-gpu:                                                                       
    build:                                                                                    
      context: .                                                                              
      dockerfile: Dockerfile                                                                  
    container_name: ollama-intel-arc-gpu                                                      
    image: ollama-intel-gpu:latest                                                            
    restart: always                                                                           
    shm_size: "32gb" # <-- not sure, if it helps                                                                 
    #privileged: true # <-- don't do it, otherwise all /dev/dri are submitted to guest                                                                                   
    devices:                                                                                  
      #- /dev/dri:/dev/dri                                                                    
      - /dev/dri/renderD129:/dev/dri/renderD129                                               
      #- /dev/dri/renderD128:/dev/dri/renderD128                                              
    volumes:                                                                                  
      - /tmp/.X11-unix:/tmp/.X11-unix                                                         
      - ollama-intel-gpu:/root/.ollama                                                        
    environment:                                                                              
      - DISPLAY=${DISPLAY}                                                                    
    env_file:                                                                                 
      - .env                                                                                  
  ollama-intel-cpu-gpu:                                                                       
    build:                                                                                    
      context: .                                                                              
      dockerfile: Dockerfile                                                                  
    container_name: ollama-intel-cpu-gpu                                                      
    image: ollama-intel-gpu:latest                                                            
    restart: always                                                                           
    shm_size: "32gb" # <-- not sure, if it helps                        
    #privileged: true   # <-- don't do it, otherwise all /dev/dri are submitted to guest                                                                    
    devices:                                                                                  
      - /dev/dri/renderD128:/dev/dri/renderD128                                               
    volumes:                                                                                  
      - /tmp/.X11-unix:/tmp/.X11-unix                                                         
      - ollama-intel-gpu:/root/.ollama                                                        
    environment:                                                                              
      - DISPLAY=${DISPLAY}                                                                    
    env_file:                                                                                 
      - .env                                                                                  
                                                                                              
  ollama-webui:                                                                               
    image: ghcr.io/open-webui/open-webui:v0.3.10                                              
    container_name: ollama-webui                                                              
    volumes:                                                                                  
      - ollama-webui:/app/backend/data                                                        
    depends_on:                                                                               
      - ollama-intel-arc-gpu                                                                  
      - ollama-intel-cpu-gpu                                                                  
    ports:                                                                                    
      - ${OLLAMA_WEBUI_PORT-3000}:8080                                                        
    environment:                                                                              
      - OLLAMA_BASE_URL=http://ollama-intel-arc-gpu:11434;http://ollama-intel-cpu-gpu:11434   
    extra_hosts:                                                                              
      - host.docker.internal:host-gateway                                                     
    restart: unless-stopped                                                                   
volumes:                                                                                      
  ollama-webui: {}                                                                            
  ollama-intel-gpu: {}                                                                        
```
